### ISSUE TITLE
keyboard shortcut for saving quotes

### ISSUE THREAD

**Issue by freegovinfo** [Blogger-Peer-Review/quotebacks#10]
Hi. I'd really like to use this extension, but the default keyboard shortcut (⌘+Shift+S) engages my zotero extension. Any way to change/set a different keyboard shortcut?

Thanks!

James

**Comment by tomcritchlow** [comment]
As per #7 - you can re-map your keyboard shortcuts at chrome://extensions/shortcuts

**Comment by freegovinfo** [comment]
thanks. apologies that I didn't look at the other issues before submitting.
