### ISSUE TITLE
Embedded in Ghost: Page does not load

### ISSUE THREAD

**Issue by jaesmail** [Blogger-Peer-Review/quotebacks#13]
I pasted the Quotebacks code into the header of my Ghost theme, and the page simply loaded as a white screen. When I removed it, the page loaded fine.

**Comment by tomcritchlow** [comment]
Hey - try pasting the embed in-line as a HTML block. It's designed to function like a twitter or youtube embed. Pasting it into the head won't work

**Comment by tobyshorin** [comment]
@jaesmail were you able to solve this?
