### ISSUE TITLE
Alt+S keyboard shortcut needs changing for Firefox

### ISSUE THREAD

**Issue by francisbarton** [Blogger-Peer-Review/quotebacks#32]
Using Firefox on Windows, Alt+S just opens the History menu and doesn't copy the quoteback text.
Using the right-click mouse menu to copy the quote works fine.
Will there be a way to change the shortcut combination for the extension please?

**Comment by tomcritchlow** [comment]
Hi Francis you can edit your extension shortcuts here: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

But thanks for the heads-up - we'll change the Firefox windows default

**Comment by francisbarton** [comment]
I just re-mapped it to Alt+Q and that didn't seem to interfere with anything else I have installed in Firefox. Works great!
