### ISSUE TITLE
Request: remove colon from file name

### ISSUE THREAD

**Issue by Jackymancs4** [Blogger-Peer-Review/quotebacks#37]
Hello,
I'm unable to clone the project on Windows (or even download and extract the zip) because of this file

https://github.com/Blogger-Peer-Review/quotebacks/blob/master/styles/scss:styles.css

which contains a colon in it's filename. 
Since colons are prohibited in filenames in Windows, git acts a little oddly.

Can you rename it?
Thanks

**Comment by tobyshorin** [comment]
Sorry about that @Jackymancs4 - we removed it from the repo now.
