### ISSUE TITLE
quotebacks.net no longer available, replaced by Namecheap domain parking site

### ISSUE THREAD

**Issue by msewell** [Blogger-Peer-Review/quotebacks#47]
As of 2021-06-07, visiting http://quotebacks.net/ greets you with this:

![image](https://user-images.githubusercontent.com/4273846/120992125-95553f80-c782-11eb-8e65-cc5f0ffc6585.png)

Has the project been abandoned?

**Comment by tomcritchlow** [comment]
No the project has not been abandoned! Apologies for the lapse - the domain is backup now
