### ISSUE TITLE
[mac extension] Key remapping or alternative usage

### ISSUE THREAD

**Issue by micimize** [Blogger-Peer-Review/quotebacks#7]
`⌘+shift+s` doesn't work. It might be being swallowed by some other key mappings on my system or another extension or something

**Comment by benrbray** [comment]
I'm having the same issue on Windows with the Chrome extension.  Nothing happens when pressing `Ctrl+Shift+S`.  Zotero also uses the `Ctrl+Shift+S` shortcut, but I disabled it and still couldn't get it working.

**Comment by tomcritchlow** [comment]
I think we can handle conflicts more gracefully in the future but for now you can re-map your chrome extension keyboard shortcuts here: chrome://extensions/shortcuts

**Comment by micimize** [comment]
@tomcritchlow remapped to `⌘+y` and it now works fine for me – didn't know about that menu 👍
