### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Fastidious** [Blogger-Peer-Review/quotebacks#8]
Haven't played with quotebacks yet, but how does it handles dark mode?

`Update @14:36:`
> I got to play with it, it doesn't handle dark mode. Can modal support for it be added using `prefers-color-scheme` on css?

**Comment by tobyshorin** [comment]
@Fastidious Dark mode support is coming in the next release. You will be able to set a flag `darkmode="true"` on the embed in order to use the dark theme!

**Comment by tobyshorin** [comment]
This is available in v1.0.4.

**Comment by Fastidious** [comment]
@tobyshorin, so, just add `darkmode="true"`, correct?

**Comment by tobyshorin** [comment]
@Fastidious hey I should probably be more specific.
`darkmode="true"` sets the whole quoteback theme to be dark. It does _not_ automatically switch from light to dark depending on user settings. The reason for this is that we do not want the quoteback to look shitty on websites which do not automatically detect user color scheme preference, and there is no reliable way to find out which websites support the feature and which do not.
